[project]
name = "analiza-danych-multimedialnych"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "kagglehub>=0.3.13",
    "numpy>=2.3.5",
    "pillow>=12.0.0",
]
